# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [2]:
# Import torch
import torch

# Create random tensor
random_tensor = torch.rand(7, 7)
random_tensor

tensor([[0.0676, 0.4822, 0.2888, 0.5064, 0.1517, 0.5420, 0.7192],
        [0.7004, 0.2127, 0.3281, 0.1861, 0.2307, 0.5320, 0.0336],
        [0.1147, 0.1524, 0.4046, 0.6970, 0.5342, 0.9639, 0.2510],
        [0.2543, 0.4506, 0.4318, 0.7768, 0.9600, 0.0507, 0.7665],
        [0.0652, 0.4203, 0.3489, 0.7899, 0.8537, 0.7688, 0.0765],
        [0.5296, 0.6883, 0.6877, 0.0814, 0.2944, 0.0734, 0.6433],
        [0.8411, 0.2863, 0.8543, 0.0930, 0.5275, 0.6428, 0.9234]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [3]:
# Create another random tensor
random_tensor2 = torch.rand(7, 7)
print(random_tensor2)

random_tensor3 = torch.rand(1, 7)
print(random_tensor3)

# Perform matrix multiplication

print(torch.matmul(random_tensor2, random_tensor3.T))

tensor([[0.8932, 0.6973, 0.0140, 0.0101, 0.5343, 0.5675, 0.0073],
        [0.9612, 0.1627, 0.5032, 0.7827, 0.5927, 0.2288, 0.3246],
        [0.6835, 0.6666, 0.0805, 0.9049, 0.0144, 0.5148, 0.2232],
        [0.6757, 0.7290, 0.7292, 0.7951, 0.8178, 0.8522, 0.4808],
        [0.4235, 0.1139, 0.3921, 0.6289, 0.1608, 0.3860, 0.7123],
        [0.3036, 0.7785, 0.0210, 0.0521, 0.4509, 0.6368, 0.6729],
        [0.8985, 0.8489, 0.7725, 0.6439, 0.2313, 0.1980, 0.2445]])
tensor([[0.8353, 0.6897, 0.1263, 0.3001, 0.2569, 0.5893, 0.5860]])
tensor([[1.7079],
        [1.6908],
        [1.7503],
        [2.3919],
        [1.3569],
        [1.6943],
        [1.9462]])


### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [4]:
# Set manual seed
RANDOM_SEED=0
torch.manual_seed(seed=RANDOM_SEED)

# Create two random tensors
random_tensor4 = torch.rand(7, 7)

random_tensor5 = torch.rand(1, 7)

# Matrix multiply tensors
print(f'{torch.matmul(random_tensor4, random_tensor5.T)}, {torch.matmul(random_tensor4, random_tensor5.T).shape}')

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]]), torch.Size([7, 1])


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [5]:
# Set random seed on the GPU
import torch
seed = 42
torch.manual_seed(seed)               # for CPU
torch.cuda.manual_seed(seed)          # for current GPU
torch.cuda.manual_seed_all(seed)      # for all GPUs (multi-GPU setup)

# For deterministic behavior (optional but useful for reproducibility)
torch.backends.cudnn.deterministic = True
torch.backends.cudnn.benchmark = False


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [6]:
# Set random seed
torch.manual_seed(1234)
torch.cuda.manual_seed(1234)

# Check for access to GPU
if torch.cuda.is_available():
    device = "cuda"
elif torch.backends.mps.is_available() and torch.backends.mps.is_built():
    device = "mps"
else:
    device = "cpu"
print(f"Device: {device}")

# Create two random tensors on GPU
tensor_A = torch.rand(2, 3).to(device)
tensor_B = torch.rand(2, 3).to(device)
tensor_A, tensor_B

Device: mps


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='mps:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='mps:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [7]:
# Perform matmul on tensor_A and tensor_B
tensor_C = torch.matmul(tensor_A, tensor_B.T)
tensor_C, tensor_C.shape

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='mps:0'),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [8]:
# Find max
max_value = torch.max(tensor_C)
print(f"Maximum value: {max_value}")
# Find min
min_value = torch.min(tensor_C)
print(f"Minimum value: {min_value}")

Maximum value: 0.5617256760597229
Minimum value: 0.3647301495075226


### 9. Find the maximum and minimum index values of the output of 7.

In [9]:
# Find arg max
max_index = torch.argmax(tensor_C)
print(f"Maximum index: {max_index}")

# Find arg min
min_index = torch.argmin(tensor_C)
print(f"Minimum index: {min_index}")

Maximum index: 3
Minimum index: 0



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [10]:
# Set seed
torch.manual_seed(7)

# Create random tensor
tensor_D = torch.rand(1, 1, 1, 10)

# Remove single dimensions
tensor_E = tensor_D.squeeze()

# Print out tensors and their shapes
print(tensor_D, tensor_D.shape)
print(tensor_E, tensor_E.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
