# 00. PyTorch Fundamentals

Course = https://www.learnpytorch.io/00_pytorch_fundamentals/

In [1]:
# Import Pytorch
import torch
torch.__version__

'2.7.0'

## Introduction to Tensors

### Creating Tensors


In [2]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
# ndim tells you how many dimensions an array has
scalar.ndim

0

In [4]:
# Get tensor back as Python int
scalar.item()

7

In [5]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX.shape

torch.Size([2, 2])

In [11]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [12]:
TENSOR.ndim

3

In [13]:
TENSOR.shape

torch.Size([1, 3, 3])

In [14]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random Tensors

Why random tensors?

The way neural networks learn is that they start with tensonrs full of random numbers and then they learn to better represent the data.

`start with random numbers -> look at data -> update random numbers -> look at data -> udpate random numbers`

In [15]:
# Create a random tensor of size (3, 4)

random_tensor = torch.rand(2, 3, 4)
random_tensor

tensor([[[0.7899, 0.7918, 0.7057, 0.8555],
         [0.9051, 0.8118, 0.3084, 0.0087],
         [0.4839, 0.0611, 0.3807, 0.1110]],

        [[0.9914, 0.9377, 0.2528, 0.0882],
         [0.3168, 0.5745, 0.3073, 0.1186],
         [0.9681, 0.8464, 0.8340, 0.4701]]])

### Zeros and ones

In [16]:
# Create a tensor of all zeros
zero = torch.zeros(size=(3, 4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [17]:
# Create a tensor of all ones
zero = torch.ones(size=(3, 4))
zero

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

### Creating a range of tensors and tensors-like

In [18]:
# Range of tensors
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
#Range of tensor-likes
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

In [20]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # what datatype is the tensor (e.g. float32 or float16)
                               device=None, # what device is your tensor on
                               requires_grad=False) # whether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [21]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [22]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

### Get attributes from tensors

1. `tensor.dtype`
2. `tensor.shape`
3. `tensor.device`

In [23]:
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.7284, 0.9093, 0.3633, 0.0884],
        [0.4033, 0.9878, 0.6598, 0.7423],
        [0.5255, 0.1561, 0.7573, 0.8224]])

In [24]:
# Find details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.7284, 0.9093, 0.3633, 0.0884],
        [0.4033, 0.9878, 0.6598, 0.7423],
        [0.5255, 0.1561, 0.7573, 0.8224]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (tensor operations)

- Addition
- Subtraction
- Multiplication
- Division
- Matrix multiplication

In [25]:
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [26]:
tensor * 10

tensor([10, 20, 30])

In [27]:
tensor - 10

tensor([-9, -8, -7])

In [28]:
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [29]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix multiplication

Two main ways of performing multiplicatoin in NN and DL

1. Element-wise multiplication
2. Matrix multiplication (dot product)

There are two main rules for matrix multiplication

1. The **inner dimensions** must match:
* `(3,2) @ (3,2)` won't work
* `(2,3) @ (3,2)` will work
* `(3,2) @ (2,3)` will work
2. The resulting matrix has the shape of the **outer dimensions**:
* `(2,3) @ (3,2) -> (2,2)`
* `(3,2) @ (2,3) -> (3,3)`

In [30]:
# Element wise multiplication

print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [31]:
# Matrix multiplication

torch.matmul(tensor, tensor)

tensor(14)

In [32]:
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

# tensor_B.T would look like this:
# tensor_B.T = torch.tensor([[7, 8, 9],
#                            [10, 11, 12]])

tensor_C = torch.tensor([[]])

# torch.mm(tensor_A, tensor_B)  -->  this would throw error
# The operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


### Finding the min, max, mean, sum, etc


In [33]:
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [34]:
torch.min(x), x.min()

(tensor(0), tensor(0))

In [35]:
torch.max(x), x.max()

(tensor(90), tensor(90))

In [36]:
# the torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [37]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [38]:
### Finding the positional min and max

In [39]:
x.argmin()

tensor(0)

In [40]:
x.argmax()

tensor(9)

### Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Same as reshape but does not change the original, just shows you how it looks with another shape
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - Return a view of an input with dimensions permuted (swapped) in a certain way


In [41]:
import torch
y = torch.arange(1,10)
y, y.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [42]:
# Add an extra dimension
y_reshaped = y.reshape(1, 9)
y_reshaped, y_reshaped.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [43]:
z = y.view(9,1)
z, z.shape

(tensor([[1],
         [2],
         [3],
         [4],
         [5],
         [6],
         [7],
         [8],
         [9]]),
 torch.Size([9, 1]))

In [44]:
# Stack tensors

y_stacked = torch.stack([y,y], dim=0)
y_stacked

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [45]:
# Stack tensors on top of each other

y_stacked2 = torch.stack([y,y], dim=1)
y_stacked2

tensor([[1, 1],
        [2, 2],
        [3, 3],
        [4, 4],
        [5, 5],
        [6, 6],
        [7, 7],
        [8, 8],
        [9, 9]])

In [46]:
# Squeeze

print(f"Previous tensor: {y_reshaped}")
print(f"Previous shape: {y_reshaped.shape}")

# Remove extra dimension from x_reshaped
y_squeezed = y_reshaped.squeeze()
print(f"\nNew tensor: {y_squeezed}")
print(f"New shape: {y_squeezed.shape}")

Previous tensor: tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
New shape: torch.Size([9])


In [47]:
# Unsqueeze

print(f"Previous tensor: {y_squeezed}")
print(f"Previous shape: {y_squeezed.shape}")

## Add an extra dimension with unsqueeze
y_unsqueezed = y_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {y_unsqueezed}")
print(f"New shape: {y_unsqueezed.shape}")

Previous tensor: tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
Previous shape: torch.Size([9])

New tensor: tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])
New shape: torch.Size([1, 9])


In [48]:
# Permute

# Create tensor with specific shape
x_original = torch.rand(size=(224, 224, 3))

# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


### Indexing (selecting data from tensors)

Similar to indexing with NumPy

In [49]:
# Create a tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [50]:
# Let's index bracket by bracket
print(f"First square bracket:\n{x[0]}")
print(f"Second square bracket: {x[0][0]}")
print(f"Third square bracket: {x[0][0][0]}")

First square bracket:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket: tensor([1, 2, 3])
Third square bracket: 1


In [51]:
# Get all values of 0th dimension and the 0 index of 1st dimension
x[:, 0]

tensor([[1, 2, 3]])

In [52]:
# Get all values of 0th & 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [53]:
# Get all values of the 0 dimension but only the 1 index value of the 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [54]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :] # same as x[0][0]

tensor([1, 2, 3])

In [55]:
# Index on x to return 9
x[0][2][2]

tensor(9)

In [56]:
# Index on x to return 3, 6, 9
x[:,:,2]

tensor([[3, 6, 9]])

### PyTorch tensors & NumPy

In [57]:
# NumPy array to tensor
import torch
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [58]:
# Change the array, keep the tensor
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [59]:
# Tensor to NumPy array
tensor = torch.ones(7) # create a tensor of ones with dtype=float32
numpy_tensor = tensor.numpy() # will be dtype=float32 unless changed
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [60]:
# Change the tensor, keep the array the same
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

### Reproducibility

[Documentation](https://docs.pytorch.org/docs/stable/notes/randomness.html)

In [61]:
import torch

# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(f"Tensor A:\n{random_tensor_A}\n")
print(f"Tensor B:\n{random_tensor_B}\n")
print(f"Does Tensor A equal Tensor B? (anywhere)")
random_tensor_A == random_tensor_B

Tensor A:
tensor([[0.3193, 0.2001, 0.3195, 0.9323],
        [0.2902, 0.4236, 0.2557, 0.5539],
        [0.0706, 0.2789, 0.0217, 0.9258]])

Tensor B:
tensor([[0.0350, 0.3072, 0.9923, 0.1414],
        [0.0736, 0.1847, 0.2356, 0.0721],
        [0.9696, 0.4678, 0.7149, 0.0334]])

Does Tensor A equal Tensor B? (anywhere)


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [62]:
import torch
import random

# # Set the random seed
RANDOM_SEED=42 # try changing this to different values and see what happens to the numbers below
torch.manual_seed(seed=RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

# Have to reset the seed every time a new rand() is called
# Without this, tensor_D would be different to tensor_C
torch.random.manual_seed(seed=RANDOM_SEED) # try commenting this line out and seeing what happens
random_tensor_D = torch.rand(3, 4)

print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C == random_tensor_D

Tensor C:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor D:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

### Running tensors on GPUs (and making faster computations)

In [63]:
!nvidia-smi

zsh:1: command not found: nvidia-smi


In [64]:
# Check for GPU
import torch
torch.cuda.is_available()

False

In [65]:
# Set device type
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [66]:
# Count number of devices
torch.cuda.device_count()

0


#### Getting PyTorch to run on Apple Silicon

In [67]:
# Check for Apple Silicon GPU
import torch
torch.backends.mps.is_available() # Note this will print false if you're not running on a Mac

True

In [68]:
# Set device type
device = "mps" if torch.backends.mps.is_available() else "cpu"
device

'mps'

In [76]:
if torch.cuda.is_available():
    device = "cuda" # Use NVIDIA GPU (if available)
elif torch.backends.mps.is_available():
    device = "mps" # Use Apple Silicon GPU (if available)
else:
    device = "cpu" # Default to CPU if no GPU is available

#### Putting tensors (and models) on the GPU

In [70]:
# Create tensor (default on CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3]) cpu


tensor([1, 2, 3], device='mps:0')

#### Moving tensors back to the CPU

In [75]:
# If tensor is on GPU, can't transform it to NumPy (this will error)
# tensor_on_gpu.numpy()

In [72]:
# Instead, copy the tensor back to cpu
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [73]:
tensor_on_gpu

tensor([1, 2, 3], device='mps:0')