# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [1]:
# Import torch
import torch

# Create random tensor
random_tensor = torch.rand(7, 7)
random_tensor

tensor([[0.1712, 0.8973, 0.6279, 0.1015, 0.3213, 0.6626, 0.6529],
        [0.2223, 0.5140, 0.4513, 0.5131, 0.9303, 0.1027, 0.2384],
        [0.4004, 0.2871, 0.3517, 0.0046, 0.7186, 0.5084, 0.5598],
        [0.6975, 0.5735, 0.9499, 0.4939, 0.0238, 0.7014, 0.0512],
        [0.0554, 0.5452, 0.7160, 0.0510, 0.0823, 0.4895, 0.6403],
        [0.8511, 0.2050, 0.4361, 0.2051, 0.0183, 0.7080, 0.1955],
        [0.1092, 0.3728, 0.4740, 0.5940, 0.3168, 0.3591, 0.5591]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [2]:
# Create another random tensor
random_tensor2 = torch.rand(7, 7)
print(random_tensor2)

random_tensor3 = torch.rand(1, 7)
print(random_tensor3)

# Perform matrix multiplication

print(torch.matmul(random_tensor2, random_tensor3.T))

tensor([[0.0761, 0.2935, 0.5795, 0.3474, 0.8004, 0.1227, 0.8163],
        [0.0253, 0.2148, 0.1141, 0.4904, 0.1158, 0.9483, 0.5669],
        [0.5110, 0.3195, 0.2338, 0.7071, 0.6657, 0.5272, 0.4472],
        [0.1116, 0.5502, 0.2293, 0.1186, 0.4628, 0.6466, 0.9610],
        [0.8101, 0.7051, 0.1990, 0.5778, 0.7123, 0.6613, 0.7812],
        [0.0308, 0.6141, 0.7719, 0.2349, 0.4570, 0.8883, 0.4756],
        [0.0952, 0.3119, 0.0820, 0.9789, 0.8905, 0.1212, 0.0628]])
tensor([[0.3315, 0.0588, 0.6456, 0.9989, 0.4071, 0.7987, 0.2183]])
tensor([[1.3657],
        [1.5128],
        [1.8352],
        [1.2505],
        [2.0043],
        [1.7787],
        [1.5537]])


### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [8]:
# Set manual seed
RANDOM_SEED=0
torch.manual_seed(seed=RANDOM_SEED)

# Create two random tensors
random_tensor4 = torch.rand(7, 7)

random_tensor5 = torch.rand(1, 7)

# Matrix multiply tensors
print(f'{torch.matmul(random_tensor4, random_tensor5.T)}, {torch.matmul(random_tensor4, random_tensor5.T).shape}')

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]]), torch.Size([7, 1])


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [ ]:
# Set random seed on the GPU
import torch
seed = 42
torch.manual_seed(seed)               # for CPU
torch.cuda.manual_seed(seed)          # for current GPU
torch.cuda.manual_seed_all(seed)      # for all GPUs (multi-GPU setup)

# For deterministic behavior (optional but useful for reproducibility)
torch.backends.cudnn.deterministic = True
torch.backends.cudnn.benchmark = False


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [13]:
# Set random seed
torch.manual_seed(1234)
torch.cuda.manual_seed(1234)

# Check for access to GPU
if torch.cuda.is_available():
    device = "cuda"
elif torch.backends.mps.is_available() and torch.backends.mps.is_built():
    device = "mps"
else:
    device = "cpu"
print(f"Device: {device}")

# Create two random tensors on GPU
tensor_A = torch.rand(2, 3).to(device)
tensor_B = torch.rand(2, 3).to(device)
tensor_A, tensor_B

Device: cuda


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [14]:
# Perform matmul on tensor_A and tensor_B
tensor_C = torch.matmul(tensor_A, tensor_B.T)
tensor_C, tensor_C.shape

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [15]:
# Find max
max_value = torch.max(tensor_C)
print(f"Maximum value: {max_value}")
# Find min
min_value = torch.min(tensor_C)
print(f"Minimum value: {min_value}")

Maximum value: 0.5617256760597229
Minimum value: 0.3647301495075226


### 9. Find the maximum and minimum index values of the output of 7.

In [17]:
# Find arg max
max_index = torch.argmax(tensor_C)
print(f"Maximum index: {max_index}")

# Find arg min
min_index = torch.argmin(tensor_C)
print(f"Minimum index: {min_index}")

Maximum index: 3
Minimum index: 0



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [18]:
# Set seed
torch.manual_seed(7)

# Create random tensor
tensor_D = torch.rand(1, 1, 1, 10)

# Remove single dimensions
tensor_E = tensor_D.squeeze()

# Print out tensors and their shapes
print(tensor_D, tensor_D.shape)
print(tensor_E, tensor_E.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
